import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-gl=angle','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1280,height:720}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:4173');await page.locator('select').first().selectOption('2');await page.locator('input[type=number]').first().fill('3');await page.locator('.seat-input select').first().selectOption('ai');await page.getByText('开始游戏',{exact:false}).first().click();await page.locator('canvas').waitFor();
const sizes=[[1536,1024],[1280,720],[390,844],[360,740]];for(const [w,h] of sizes){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(1000);const box=await page.locator('.board-wrap').boundingBox(),labels=await page.locator('.city-label').count(),overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await page.screenshot({path:`test-${w}x${h}.png`,fullPage:true});console.log('size',w,h,'board',Math.round(box.width),Math.round(box.height),'labels',labels,'horizontalOverflow',overflow)}
await page.setViewportSize({width:1280,height:720});await page.waitForTimeout(1000);const canvas=page.locator('canvas'),box=await canvas.boundingBox();
const sample=async(ms)=>page.evaluate(ms=>new Promise(resolve=>{let n=0,start=performance.now();function f(){n++;if(performance.now()-start<ms)requestAnimationFrame(f);else resolve(Math.round(n*1000/(performance.now()-start)))}requestAnimationFrame(f)}),ms);
const fps=sample(1800);await page.mouse.move(box.x+box.width*.45,box.y+box.height*.45);await page.mouse.down();for(let i=0;i<20;i++)await page.mouse.move(box.x+box.width*(.45+i*.01),box.y+box.height*.45);await page.mouse.up();console.log('drag fps',await fps);
await page.waitForTimeout(1500);await page.reload();await page.locator('canvas').waitFor();console.log('saved round',await page.locator('.round-badge').textContent());
await page.waitForFunction(()=>!!document.querySelector('.result-card'),null,{timeout:90000}).catch(()=>{});console.log('ai finished',await page.locator('.result-card').count(),'phase',await page.locator('.phase-note').textContent(),'errors',errors);await browser.close();
