import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,applyAction,linked,rent,wealth} from '../shared/game.js';

const fixed=(a,b)=>{let i=0;return ()=>[a,b][i++%2]};
test('three players rotate across rounds and end at round cap',()=>{let s=createGame({count:3,rounds:3});assert.equal(s.players.length,3);for(let i=0;i<9;i++){s=applyAction(s,{type:'roll'},fixed(0,0));if(s.phase==='decision')s=applyAction(s,{type:'skip'});s=applyAction(s,{type:'end'});if(i<8)assert.equal(s.current,(i+1)%3)}assert.equal(s.phase,'gameover');assert.equal(s.round,4)});
test('buy, build and full region links increase rent',()=>{let s=createGame({count:3});s.current=0;s.phase='decision';s.pending={kind:'buy',id:1};s=applyAction(s,{type:'buy'});assert.equal(s.properties[1].owner,0);s=applyAction(s,{type:'build',id:1});assert.equal(s.properties[1].level,1);const before=rent(s,1);s.properties[2]={owner:0,level:0,mortgaged:false};s.properties[4]={owner:0,level:0,mortgaged:false};assert.equal(linked(s,0,'京津冀'),true);assert.ok(rent(s,1)>before);s=applyAction(s,{type:'mortgage',id:2});assert.equal(linked(s,0,'京津冀'),false);s=applyAction(s,{type:'redeem',id:2});assert.equal(linked(s,0,'京津冀'),true)});
test('unpaid rent is credited only when recovered; bankruptcy returns property',()=>{let s=createGame({count:2,cash:500});s.players[0].cash=20;s.properties[9]={owner:1,level:3,mortgaged:false};s.properties[2]={owner:0,level:0,mortgaged:false};s.players[0].pos=7;s=applyAction(s,{type:'roll'},fixed(0,0));assert.equal(s.phase,'debt');assert.equal(s.players[1].cash,520);s=applyAction(s,{type:'mortgage',id:2});assert.ok(s.players[1].cash>520);if(s.phase==='debt')s=applyAction(s,{type:'bankrupt'});assert.equal(s.players[0].bankrupt,true);assert.equal(s.properties[2],undefined)});
test('jail, fortune and misfortune have effects',()=>{let s=createGame({count:2});s.players[0].jailed=1;s.players[0].pos=8;s=applyAction(s,{type:'roll'},fixed(0,.5));assert.equal(s.players[0].jailed,1);assert.equal(s.phase,'finish');s=applyAction(s,{type:'end'});s.current=0;s.phase='roll';s=applyAction(s,{type:'bail'});assert.equal(s.players[0].jailed,0);s.players[0].pos=13;s=applyAction(s,{type:'roll'},fixed(0,0));assert.ok(s.players[0].fortune>0);s=applyAction(s,{type:'end'});s.current=0;s.phase='roll';s.players[0].pos=25;s=applyAction(s,{type:'roll'},fixed(0,0));assert.ok(s.players[0].misfortune>0);assert.equal(s.players[0].fortune,0)});
