import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Html,ContactShadows,Text} from '@react-three/drei';
import * as THREE from 'three';
import {BOARD,REGIONS} from '../shared/board.js';
import {linked} from '../shared/game.js';

export function tilePosition(i){const a=1.68;if(i<=8)return [-6.72+i*a,-6.72];if(i<=16)return [6.72,-6.72+(i-8)*a];if(i<=24)return [6.72-(i-16)*a,6.72];return [-6.72,6.72-(i-24)*a]}
function Box({position,args,color,rotation,metalness=0,...rest}){return <mesh position={position} rotation={rotation} castShadow receiveShadow {...rest}><boxGeometry args={args}/><meshStandardMaterial color={color} roughness={.65} metalness={metalness}/></mesh>}
function Roof({position=[0,0,0],width=1.1,depth=.8,color='#184d85'}){return <group position={position}><mesh rotation={[0,0,Math.PI/4]} castShadow><boxGeometry args={[width*.32,width*.32,depth]}/><meshStandardMaterial color={color}/></mesh><Box position={[0,.02,0]} args={[width,.07,depth+.12]} color={color}/><Box position={[0,.13,0]} args={[width+.12,.045,depth+.12]} color="#d3aa54"/></group>}
function ChinaHouse({level=0,color='#d94938',position=[0,0,0],scale=.75}){const floors=[1,2,4,6][level],height=[.34,.62,1.14,1.65][level];return <group position={position} scale={scale}><Box position={[0,height/2,0]} args={[.9,height,.7]} color={level>=2?'#e8d6ab':'#f5e5c1'}/>{Array.from({length:floors},(_,i)=><group key={i}>{[-.24,0,.24].map((x,j)=><Box key={j} position={[x,.18+i*(height-.2)/floors,.357]} args={[.1,.12,.02]} color="#307598"/>)}<Box position={[.455,.18+i*(height-.2)/floors,0]} args={[.02,.12,.18]} color="#307598"/></group>)}<Roof position={[0,height+.08,0]} width={level>=2?1.05:1.17} color={color}/>{level>=2&&<Box position={[0,height+.28,0]} args={[.3,.12,.22]} color="#c6a25d"/>}</group>}
function GrowingHouse(props){const group=useRef(),progress=useRef(0);useFrame((_,delta)=>{if(progress.current>=1.15)return;progress.current=Math.min(1.15,progress.current+delta*2.4);const t=progress.current<1?1-(1-progress.current)**3:1+(1.15-progress.current)*.16;group.current.scale.y=Math.max(.05,t)});return <group ref={group}><ChinaHouse {...props}/>{[0,1,2,3,4].map(i=><mesh key={i} position={[Math.cos(i*1.26)*.31,.24+(.1*i),Math.sin(i*1.26)*.31]}><sphereGeometry args={[.025,6,6]}/><meshStandardMaterial color="#f4cb55" emissive="#e2a83a" emissiveIntensity={.5}/></mesh>)}</group>}
function Pagoda({position=[0,0,0],scale=1,color='#c94334'}){return <group position={position} scale={scale}><Box position={[0,.42,0]} args={[1.1,.84,.9]} color="#f1dca7"/><Box position={[0,.85,0]} args={[1.25,.14,1.08]} color={color}/><Box position={[0,1.02,0]} args={[.72,.42,.63]} color="#f1dca7"/><Box position={[0,1.29,0]} args={[.92,.14,.82]} color={color}/><Box position={[0,1.39,0]} args={[.45,.18,.4]} color="#f1dca7"/><mesh position={[0,1.59,0]} castShadow><coneGeometry args={[.45,.38,4]}/><meshStandardMaterial color={color}/></mesh></group>}
function Temple(){return <group position={[-1.6,0,-.7]}><mesh position={[0,.1,0]} receiveShadow><cylinderGeometry args={[1.75,1.85,.2,48]}/><meshStandardMaterial color="#e8d2a1"/></mesh>{[0,1,2].map((n)=><group key={n} position={[0,.18+n*.38,0]}><mesh castShadow><cylinderGeometry args={[1.35-n*.22,1.45-n*.22,.36,32]}/><meshStandardMaterial color="#c9ab73"/></mesh><mesh position={[0,.24,0]} castShadow><coneGeometry args={[1.48-n*.2,.33,32]}/><meshStandardMaterial color="#1769a1"/></mesh></group>)}<mesh position={[0,1.58,0]}><sphereGeometry args={[.11,12,12]}/><meshStandardMaterial color="#e4bb59"/></mesh></group>}
function Pearl(){return <group position={[2.5,0,-1.8]}><mesh position={[0,1.65,0]} castShadow><cylinderGeometry args={[.14,.23,3.3,16]}/><meshStandardMaterial color="#e9e8d9"/></mesh>{[.7,1.85,2.65].map((h,i)=><mesh key={i} position={[0,h,0]} castShadow><sphereGeometry args={[[.33,.47,.23][i],20,16]}/><meshStandardMaterial color="#b2589e" metalness={.25} roughness={.35}/></mesh>)}<mesh position={[0,3.39,0]}><coneGeometry args={[.06,.85,12]}/><meshStandardMaterial color="#e7dcb1"/></mesh></group>}
function CantonTower(){return <group position={[2.9,0,2]}><mesh position={[0,1.7,0]} castShadow><cylinderGeometry args={[.13,.36,3.4,16]}/><meshStandardMaterial color="#e1b66f" wireframe/></mesh>{[.4,1,1.6,2.2,2.8,3.25].map((h,i)=><mesh key={i} position={[0,h,0]}><torusGeometry args={[[.3,.23,.15,.21,.31,.16][i],.035,8,18]}/><meshStandardMaterial color="#bd5b43"/></mesh>)}<mesh position={[0,3.7,0]}><cylinderGeometry args={[.035,.09,.8,10]}/><meshStandardMaterial color="#bd5b43"/></mesh></group>}
function Tree({position,scale=1}){return <group position={position} scale={scale}><mesh position={[0,.25,0]} castShadow><cylinderGeometry args={[.045,.07,.5,8]}/><meshStandardMaterial color="#895b39"/></mesh><mesh position={[0,.65,0]} castShadow><sphereGeometry args={[.32,12,9]}/><meshStandardMaterial color="#318563"/></mesh><mesh position={[.15,.82,.05]} castShadow><sphereGeometry args={[.2,10,8]}/><meshStandardMaterial color="#58a96b"/></mesh></group>}
function Lantern({position}){return <group position={position}><mesh position={[0,.48,0]}><cylinderGeometry args={[.035,.04,.95,8]}/><meshStandardMaterial color="#695343"/></mesh><mesh position={[0,1.03,0]} castShadow><sphereGeometry args={[.16,12,10]}/><meshStandardMaterial color="#dc3a2e"/></mesh><mesh position={[0,1.22,0]}><coneGeometry args={[.07,.12,8]}/><meshStandardMaterial color="#f1ca68"/></mesh></group>}
function CenterCity(){return <group><Box position={[0,-.01,0]} args={[10.9,.16,10.9]} color="#d6e2c1"/><Box position={[0,.07,0]} args={[9.8,.03,.65]} color="#5aa8b1" rotation={[0,.28,0]}/><Box position={[0,.07,0]} args={[.48,.03,9.3]} color="#5aa8b1" rotation={[0,.28,0]}/><Temple/><Pearl/><CantonTower/><Pagoda position={[-3.5,0,2.2]} scale={1.25}/><Pagoda position={[.65,0,2.5]} scale={.72} color="#286d88"/><Pagoda position={[.4,0,-3.35]} scale={.66} color="#bc543d"/>{[[-4,0,-3.7],[-3.8,0,-1.6],[-4,0,3.9],[-1.7,0,3.8],[1,0,4],[4,0,3.8],[4,0,.2],[4,0,-3.9],[.6,0,-4.1],[-2.8,0,-4.1]].map((p,i)=><Tree key={i} position={p} scale={.8+(i%3)*.14}/>)}{[[-2.6,0,2.8],[.9,0,-2.6],[3.6,0,3.1]].map((p,i)=><Lantern key={i} position={p}/>)}<Box position={[-.03,.13,0]} args={[.9,.1,2]} color="#d8b57a" rotation={[0,.28,0]}/><Text position={[0,.04,.5]} rotation={[-Math.PI/2,0,0]} fontSize={.46} color="#6a422b" anchorX="center">神州大富翁</Text></group>}
function Figure({position,color,active,offset=0}){return <group position={[position[0]+offset,.16,position[1]+.15]}><mesh position={[0,.28,0]} castShadow><cylinderGeometry args={[.12,.16,.42,12]}/><meshStandardMaterial color={color}/></mesh><mesh position={[0,.61,0]} castShadow><sphereGeometry args={[.17,16,12]}/><meshStandardMaterial color="#f4d3ac"/></mesh><mesh position={[0,.13,.09]} castShadow><boxGeometry args={[.09,.23,.12]}/><meshStandardMaterial color="#304d65"/></mesh><mesh position={[.12,.13,.09]} castShadow><boxGeometry args={[.09,.23,.12]}/><meshStandardMaterial color="#304d65"/></mesh><mesh position={[-.19,.33,0]} rotation={[0,0,-.5]}><capsuleGeometry args={[.055,.25,4,8]}/><meshStandardMaterial color={color}/></mesh><mesh position={[.19,.33,0]} rotation={[0,0,.5]}><capsuleGeometry args={[.055,.25,4,8]}/><meshStandardMaterial color={color}/></mesh>{active&&<mesh position={[0,1.1,0]} rotation={[Math.PI,0,0]}><coneGeometry args={[.17,.25,4]}/><meshStandardMaterial color="#f5cd4b" emissive="#8b5c1b" emissiveIntensity={.3}/></mesh>}</group>}
function Tile({id,state,onSelect,selected}){const t=BOARD[id],p=state.properties[id],pos=tilePosition(id),color=t.region?REGIONS[t.region]:({start:'#d8553a',event:'#a06db5',fortune:'#e9b448',misfortune:'#657688',rail:'#4d8da9',jail:'#9f765b',gojail:'#a8645b',park:'#65aa7b',fee:'#b8865a'}[t.type]||'#9ab27b');return <group position={[pos[0],0,pos[1]]} onClick={e=>{e.stopPropagation();onSelect(id)}}><Box position={[0,-.04,0]} args={[1.58,.19,1.58]} color={selected?'#f3c651':'#e7dac0'}/><Box position={[0,.075,0]} args={[1.48,.06,1.48]} color="#fff8e8"/><Box position={[0,.113,-.53]} args={[1.48,.055,.31]} color={p?state.players[p.owner].color:color}/>{p&&<Box position={[0,.11,.69]} args={[1.47,.08,.09]} color={state.players[p.owner].color}/>}<Text position={[0,.153,-.37]} rotation={[-Math.PI/2,0,0]} fontSize={.22} fontWeight={700} color="#233b40" anchorX="center" maxWidth={1.35}>{t.name.replace(' · ',' ')}</Text><Text position={[0,.155,.34]} rotation={[-Math.PI/2,0,0]} fontSize={.21} color="#263b3c" fontWeight={700}>{t.price?`¥${t.price}`:({start:'GO +¥200',event:'?',fortune:'福',misfortune:'!',rail:'🚄',jail:'探望',gojail:'入狱',park:'休憩',fee:'-¥120'}[t.type]||'')}</Text>{(t.type==='city'&&p)&&<GrowingHouse key={`${id}-${p.level}`} level={p.level} color={state.players[p.owner].color} position={[.47,.14,.32]} scale={.49}/>} {p&&<mesh position={[-.62,.29,.56]}><cylinderGeometry args={[.045,.045,.32,8]}/><meshStandardMaterial color="#595043"/></mesh>}{p&&<Box position={[-.62,.43,.56]} args={[.23,.15,.025]} color={state.players[p.owner].color}/>} {t.type==='city'&&!p&&<ChinaHouse level={0} color={color} position={[.47,.14,.35]} scale={.34}/>} {t.region&&linked(state,p?.owner,t.region)&&p&&!p.mortgaged&&<mesh position={[0,.12,.68]}><sphereGeometry args={[.075,10,8]}/><meshStandardMaterial color="#f7c843" emissive="#ad6e13" emissiveIntensity={.6}/></mesh>}</group>}
function CameraButtons({controlRef,viewCommand}){const {size}=useThree();useEffect(()=>{const c=controlRef.current;if(!c)return;const command=viewCommand.split('-')[0];if(command==='reset'){c.object.position.set(...(size.width<600?[25,30,30]:[15,19,19]));c.target.set(0,0,0);c.update()}else if(command==='left'||command==='right'){c.setAzimuthalAngle(c.getAzimuthalAngle()+(command==='left'?.45:-.45));c.update()}else if(command==='in'||command==='out'){c.object.position.multiplyScalar(command==='in'?.78:1.28);c.update()}},[viewCommand]);return null}
function CameraLayout({controlRef}){const {size}=useThree();useEffect(()=>{const c=controlRef.current;if(!c)return;if(size.width<600)c.object.position.set(25,30,30);else c.object.position.set(15,19,19);c.update()},[size.width,controlRef]);return null}
function projectLabels(camera,size){camera.updateMatrixWorld();const placed=[];const labels=BOARD.flatMap((tile,id)=>{if(tile.type!=='city')return[];const [x,z]=tilePosition(id),v=new THREE.Vector3(x,.75,z).project(camera);return [{id,x:(v.x*.5+.5)*size.width,y:(-v.y*.5+.5)*size.height}]});for(const item of labels){const width=52,height=21;let found=null;for(const dy of [0,-23,23,-46,46,-69,69]){for(const dx of [0,-26,26]){const x=Math.max(3,Math.min(size.width-width-3,item.x-width/2+dx)),y=Math.max(3,Math.min(size.height-height-3,item.y-height/2+dy));if(!placed.some(p=>x<p.x+width+2&&x+width+2>p.x&&y<p.y+height+2&&y+height+2>p.y)){found={id:item.id,x,y};break}}if(found)break}placed.push(found||{id:item.id,x:Math.max(3,Math.min(size.width-width-3,item.x-width/2)),y:Math.max(3,Math.min(size.height-height-3,item.y-height/2))})}return placed}
function LabelTracker({onPositions}){const {camera,size}=useThree(),frame=useRef(0);useEffect(()=>{onPositions(projectLabels(camera,size))},[camera,size.width,size.height]);useFrame(()=>{if(++frame.current%3===0)onPositions(projectLabels(camera,size))});return null}
export function BoardScene({state,onSelect,selected,viewCommand,displayPositions}){const control=useRef(),[labels,setLabels]=useState([]);return <div className="scene-container"><Canvas shadows dpr={[1,1.25]} camera={{position:[15,19,19],fov:43,near:.1,far:100}} gl={{antialias:true,alpha:true}}><color attach="background" args={['#d9e5dc']}/><ambientLight intensity={1.55}/><hemisphereLight intensity={1.15} groundColor="#b7a07a"/><directionalLight position={[-8,19,10]} intensity={2.1} castShadow shadow-mapSize={[1024,1024]} shadow-camera-left={-15} shadow-camera-right={15} shadow-camera-top={15} shadow-camera-bottom={-15} shadow-bias={-.0002}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.2,0]} receiveShadow><planeGeometry args={[80,80]}/><meshStandardMaterial color="#c3d2bb"/></mesh><Box position={[0,-.16,0]} args={[15.6,.29,15.6]} color="#bda983"/><CenterCity/>{BOARD.map((_,i)=><Tile key={i} id={i} state={state} selected={selected===i} onSelect={onSelect}/>)}{state.players.filter(p=>!p.bankrupt).map((p,i)=><Figure key={p.id} color={p.color} position={tilePosition(displayPositions?.[p.id]??p.pos)} offset={(i%4-1.5)*.18} active={state.current===p.id}/>)}<OrbitControls ref={control} enablePan={false} minDistance={16} maxDistance={50} maxPolarAngle={Math.PI*.46} minPolarAngle={.48} target={[0,0,0]}/><CameraLayout controlRef={control}/><CameraButtons controlRef={control} viewCommand={viewCommand}/><LabelTracker onPositions={setLabels}/></Canvas><div className="city-labels">{labels.map(l=><button key={l.id} className={`city-label ${selected===l.id?'selected':''}`} style={{left:l.x,top:l.y,borderColor:REGIONS[BOARD[l.id].region]}} onClick={()=>onSelect(l.id)}>{BOARD[l.id].name}</button>)}</div></div>}
